version: '3.8'
#the container images that we want to start
services:
  postgres:
    image: postgres:13.3-alpine
    ports:
      - '5432:5432'
      #volumes:
      # -"./postgres:/var/libpostgresql/data"

    environment:
      POSTGRES_USER: 'sq008'
      POSTGRES_PASSWORD: 'sq008'
      POSTGRES_DB: 'sq008'

    healthcheck:
      interval: 10s
      retries: 3
      timeout: 2s
      test:
        ['/usr/bin/pg_isready', '-U', 'postgres', '--silent', '-d', 'postgres']
